# Generated by Django 2.2.16 on 2021-03-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ui', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruiuserinput',
            name='started_at',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useruiuserinput',
            name='time_taken',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
